### ISSUE TITLE
Criteria before transfer to ropensci?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/pkgreviewr#56]
The repo should eventually be transferred to ropensci, maybe after doing the following:

- [ ] Removing the use of unexported functions #3 
- [x] README overhaul #26 

Once we transferred the repo, @annakrystalli would you like to write a tech note about the package? (or a blog post? cc @stefaniebutland )

**Comment by annakrystalli** [comment]
I would add some extra tests too to cover `editor` templates too (#57)

**Comment by stefaniebutland** [comment]
> would you like to write a tech note about the package? (or a blog post? cc @stefaniebutland )

Let me know what you think @annakrystalli!

**Comment by annakrystalli** [comment]
Sure  @stefaniebutland!  

PS @maelle what is a tech note?

**Comment by maelle** [comment]
shorter (but not necessarily) and more technical than blog posts https://ropensci.org/technotes/
