### ISSUE TITLE
Error when setting up a new editor review

### ISSUE THREAD

**Issue by adamhsparks** [ropensci-org/pkgreviewr#79]
```r
> pkgreview_create("popecol/rangr",
                  review_parent = "~/Developer/GitHub/rOpenSci/reviews/",
                  template = "editor",
                  issue_no = 595)
```

Clones the repo to the correct directory but then errors with:

```r
Error in pkgreview_getdata(pkg_dir = pkg_dir, pkg_repo, template = template,  : 
  object 'package_data' not found
```

The examples do the same when I run them as-is and put the repo in "~/Documents".

**Comment by Pakillo** [comment]
I'm finding the same problem. I think the error stems from using a now deprecated usethis function [here](https://github.com/ropensci-org/pkgreviewr/blob/ac206ea34f79ead0362c0bb6b4ce026ebeedbf15/R/pkgreview.R#L175) (see https://github.com/r-lib/usethis/pull/1747). AFAIK there was nothing wrong with `project_data`, it was just an API change.  

I tried and the problem could be fixed easily by adding the now removed `usethis:::project_data()` function as an internal function in `pkgreviewr` (e.g. at the end of `utils.R`), without having to rewrite anything else. Please let me know if you'd welcome a pull request with that fix.

**Comment by annakrystalli** [comment]
Thanks for digging into this @Pakillo ! I would ❤️ a pull request!
